$init_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7
  service mysql restart
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "private_network", ip: "10.0.0.10"
    mysqlserver.vm.network "forwarded_port", guest: 8080, host: 8080
    mysqlserver.vm.provider "hyperv" do |hyv|
      hyv.name = "mysqlserver"
    end
  end
end
